services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: user_management_backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: SD2025COOLGROUP_JWT_SECRET_KEY_$(date +%s)
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
    ports:
      - "5000:5000"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: user_management_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: user_management_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
